import './globals.css'

import { Plus_Jakarta_Sans } from 'next/font/google'
import React from 'react'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Porfolio | Cleilton Rocha',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${plusJakartaSans.className} bg-neutral-950`}>
        {children}
      </body>
    </html>
  )
}
